name: Generate a build and push to another branch

on: 
  workflow_run:
    workflows: ["testing"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm run build